export const FETCH_MOSTPOPULAR_FULFILLED = 'FETCH_MOSTPOPULAR_FULFILLED';
export const FETCH_UPCOMING_FULFILLED = 'FETCH_UPCOMING_FULFILLED';
export const FETCH_POPULARPEOPLE_FULFILLED = 'FETCH_POPULARPEOPLE_FULFILLED';
export const FETCH_MOSTPOPULAR_TVSHOWS_FULFILLED = 'FETCH_MOSTPOPULAR_TVSHOWS_FULFILLED';
export const FETCH_CURRENT_TVSHOWS_FULFILLED = 'FETCH_CURRENT_TVSHOWS_FULFILLED';
export const FETCH_SEARCH_FULFILLED = 'FETCH_SEARCH_FULFILLED';
export const IS_USER_AUTH = 'IS_USER_AUTH';
